service_account_id: "your-service-account-id-here"
jwk_json: '{"kty":"RSA","use":"sig","kid":"example123","n":"example-n-value...","e":"AQAB","d":"example-d-value..."}'
platform: "https://your-forgerock-platform.com"
scope: "fr:am:* fr:idm:*"
exp_seconds: 899
proxy: null
verbose: false
output_format: "token"
verify_ssl: true